#!/bin/bash

echo "Please enter your username: "

read -s Username

echo "Username entered is :: $Username"

cho "Please enter your password: "

read -s Password

echo "Password entered is :: $Password"